image: alpine:latest

stages:
  - deploy-gas

deploy-gas:
  stage: deploy-gas
  rules: 
  - if: $CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"
  before_script:
  - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan $VM_IPADDRESS >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh -v "$SSH_USER@$VM_IPADDRESS" 'cd /home/hezhin/domains/gasapi.hezhin.dev/public_html && git reset --hard && git pull origin master && /home/hezhin/composer update && php artisan migrate'